import {
  LayoutDashboard, ShoppingCart, Grid, ShoppingBag, Monitor, Wallet, History, Truck,
  FolderTree, PackageOpen, Plus, Leaf, Megaphone, BarChart3, Package, Barcode,
  ListChecks, RotateCcw, ClipboardCheck, ClipboardList, FileText, Settings2,
  PieChart, Gift, DollarSign, Building2, Settings, Users, ShieldCheck, BookOpen,
  UserCircle, GraduationCap, BarChart2, MessageSquare, Headphones, CalendarDays,
  CalendarRange, Video, HelpCircle, Bot, Gauge, Trophy, Activity, Network, Bell,
  Store, CalendarCheck, CalendarClock, LayoutGrid, Layers, Landmark, FileBarChart,
  TrendingUp, Receipt, FolderOpen, Banknote, ReceiptText
} from 'lucide-react';
import React from 'react';

// Mapeamento de rotas para ícones do Lucide
export const routeIcons: Record<string, React.ComponentType<any>> = {
  '/admin/dashboard': LayoutDashboard,
  '/admin/pdv/nova-venda': ShoppingCart,
  '/admin/pdv/mesas': Grid,
  '/admin/orders': ShoppingBag,
  '/admin/kds': Monitor,
  '/admin/pdv/caixa': Wallet,
  '/admin/pdv/caixa/historico': History,
  '/admin/delivery': Truck,
  '/admin/menu/categories': FolderTree,
  '/admin/menu/products': PackageOpen,
  '/admin/menu/toppings': Plus,
  '/admin/menu/ingredients': Leaf,
  '/admin/promotions': Megaphone,
  '/admin/stock/dashboard': BarChart3,
  '/admin/stock/inventory': Package,
  '/admin/stock/movements': History,
  '/admin/stock/counts': Barcode,
  '/admin/checkgrau/grupos-contagem': ListChecks,
  '/admin/checkgrau/contagens-recorrentes': RotateCcw,
  '/admin/stock/purchases': ShoppingCart,
  '/admin/stock/purchase-history': ClipboardCheck,
  '/admin/stock/checklists/execution': ClipboardList,
  '/admin/stock/checklists/reports': FileText,
  '/admin/stock/checklists/admin': Settings2,
  '/admin/stock/cmv': PieChart,
  '/admin/stock/bonificacoes': Gift,
  '/admin/financeiro': DollarSign,
  '/admin/pdv/relatorios': BarChart3,
  '/admin/fiscal': FileText,
  '/admin/fiscal/dashboard': FileText,
  '/admin/fiscal/historico': FileText,
  '/admin/analytics': BarChart3,
  '/admin/marketing': Megaphone,
  '/admin/feedback': MessageSquare,
  '/admin/orders/catalog': ShoppingCart,
  '/admin/orders/history': History,
  '/admin/orders/management': Package,
  '/admin/orders/reports': BarChart2,
  '/admin/orders/products': Grid,
  '/admin/franchisees': Building2,
  '/admin/loja/dados': Building2,
  '/admin/pdv/configuracoes': Settings,
  '/admin/settings': Settings,
  '/admin/delivery/areas': Truck,
  '/admin/settings/usuarios': Users,
  '/admin/settings/seguranca': ShieldCheck,
  '/admin/help': BookOpen,
  '/admin/meu-perfil': UserCircle,
  '/admin/universidade': GraduationCap,
  '/admin/universidade/admin': Settings2,
  '/admin/frota': Truck,
  '/admin/performance': BarChart2,
  '/admin/assistente': Bot,

  // CheckGrau
  '/admin/checkgrau': Gauge,
  '/admin/checkgrau/rankings': Trophy,
  '/admin/checkgrau/desempenho': Users,
  '/admin/checkgrau/engajamento': Activity,
  '/admin/checkgrau/rede': Network,
  '/admin/checkgrau/alertas': Bell,
  '/admin/checkgrau/mensagens': MessageSquare,
  '/admin/checkgrau/relatorios': BarChart3,
  '/admin/checkgrau/stores': Store,
  '/admin/checkgrau/collaborators': Users,
  '/admin/checkgrau/agenda': CalendarCheck,
  '/admin/checkgrau/rotinas': CalendarClock,
  '/admin/checkgrau/checklists': ClipboardCheck,
  '/admin/checkgrau/setores-turnos': LayoutGrid,

  // Financeiro
  '/admin/financeiro/caixa': Landmark,
  '/admin/financeiro/fluxo': TrendingUp,
  '/admin/financeiro/fluxo-semanal': CalendarRange,
  '/admin/financeiro/lancamentos': Receipt,
  '/admin/financeiro/receber': Banknote,
  '/admin/financeiro/recibos': ReceiptText,
  '/admin/financeiro/despesas': Wallet,
  '/admin/financeiro/dre': BarChart3,
  '/admin/financeiro/relatorios': FileBarChart,
  '/admin/financeiro/receitas-despesas': LayoutDashboard,
  '/admin/financeiro/despesas-detalhadas': BarChart3,
  '/admin/financeiro/cadastros': FolderOpen,
  '/admin/financeiro/configuracoes': Settings
};

// Mapeamento de cores de destaque por módulo (em Tailwind classes)
export const routeColors: Record<string, string> = {
  '/admin/dashboard': 'indigo-600',
  '/admin/pdv/nova-venda': 'blue-600',
  '/admin/pdv/mesas': 'blue-600',
  '/admin/pdv/caixa': 'blue-600',
  '/admin/orders': 'purple-600',
  '/admin/kds': 'amber-600',
  '/admin/delivery': 'sky-600',
  '/admin/financeiro': 'emerald-600',
  '/admin/fiscal/dashboard': 'rose-600',
  '/admin/fiscal/historico': 'rose-600',
  '/admin/analytics': 'teal-600',
  '/admin/stock/dashboard': 'orange-600',
  '/admin/stock/inventory': 'orange-600',
  '/admin/stock/purchases': 'orange-600',
  '/admin/marketing': 'pink-600',
  '/admin/assistente': 'violet-600',
  '/admin/settings/usuarios': 'cyan-600',
  '/admin/universidade': 'red-600',

  // CheckGrau routes
  '/admin/checkgrau': 'purple-600',
  '/admin/checkgrau/rankings': 'purple-600',
  '/admin/checkgrau/desempenho': 'purple-600',
  '/admin/checkgrau/engajamento': 'purple-600',
  '/admin/checkgrau/rede': 'purple-600',
  '/admin/checkgrau/alertas': 'purple-600',
  '/admin/checkgrau/mensagens': 'purple-600',
  '/admin/checkgrau/relatorios': 'purple-600',
  '/admin/checkgrau/stores': 'purple-600',
  '/admin/checkgrau/collaborators': 'purple-600',
  '/admin/checkgrau/agenda': 'purple-600',
  '/admin/checkgrau/rotinas': 'purple-600',
  '/admin/checkgrau/checklists': 'purple-600',
  '/admin/checkgrau/setores-turnos': 'purple-600',

  // Financeiro routes
  '/admin/financeiro/caixa': 'emerald-600',
  '/admin/financeiro/fluxo': 'emerald-600',
  '/admin/financeiro/fluxo-semanal': 'emerald-600',
  '/admin/financeiro/lancamentos': 'emerald-600',
  '/admin/financeiro/receber': 'emerald-600',
  '/admin/financeiro/recibos': 'emerald-600',
  '/admin/financeiro/despesas': 'emerald-600',
  '/admin/financeiro/dre': 'emerald-600',
  '/admin/financeiro/relatorios': 'emerald-600',
  '/admin/financeiro/receitas-despesas': 'emerald-600',
  '/admin/financeiro/despesas-detalhadas': 'emerald-600',
  '/admin/financeiro/cadastros': 'emerald-600',
  '/admin/financeiro/configuracoes': 'emerald-600'
};

export const defaultIcon = HelpCircle;
export const defaultColor = 'zinc-600';
