export const routeTitles: Record<string, string> = {
  '/admin/dashboard': 'Dashboard',
  '/admin/pdv/nova-venda': 'PDV [BALCÃO]',
  '/admin/pdv/mesas': 'Mesas',
  '/admin/orders': 'Pedidos',
  '/admin/kds': 'KDS Cozinha',
  '/admin/pdv/caixa': 'Caixa',
  '/admin/pdv/caixa/historico': 'Histórico de Turnos',
  '/admin/delivery': 'Entregas',
  '/admin/menu/categories': 'Categorias',
  '/admin/menu/products': 'Produtos',
  '/admin/menu/toppings': 'Complementos',
  '/admin/menu/ingredients': 'Ingredientes',
  '/admin/promotions': 'Promoções',
  '/admin/stock/dashboard': 'Painel Estoque',
  '/admin/stock/inventory': 'Estoque Central',
  '/admin/stock/movements': 'Movimentações',
  '/admin/stock/counts': 'Contagem (Inventário)',
  
  // CheckGrau
  '/admin/checkgrau': 'Painel CheckNoGrau',
  '/admin/checkgrau/rankings': 'Rankings CheckNoGrau',
  '/admin/checkgrau/desempenho': 'Desempenho de Operações',
  '/admin/checkgrau/engajamento': 'Engajamento CheckNoGrau',
  '/admin/checkgrau/rede': 'Rede CheckNoGrau',
  '/admin/checkgrau/alertas': 'Alertas CheckNoGrau',
  '/admin/checkgrau/mensagens': 'Mensagens CheckNoGrau',
  '/admin/checkgrau/relatorios': 'Relatórios CheckNoGrau',
  '/admin/checkgrau/stores': 'Lojas CheckNoGrau',
  '/admin/checkgrau/collaborators': 'Colaboradores CheckNoGrau',
  '/admin/checkgrau/agenda': 'Agenda CheckNoGrau',
  '/admin/checkgrau/rotinas': 'Rotinas CheckNoGrau',
  '/admin/checkgrau/checklists': 'Checklists CheckNoGrau',
  '/admin/checkgrau/setores-turnos': 'Setores & Turnos',
  '/admin/checkgrau/grupos-contagem': 'Grupos de Contagem',
  '/admin/checkgrau/contagens-recorrentes': 'Contagem Recorrente',

  '/admin/stock/purchases': 'Lista de compras',
  '/admin/stock/purchase-history': 'Histórico de Compras',
  '/admin/stock/checklists/execution': 'Rotinas Operacionais',
  '/admin/stock/checklists/reports': 'Relatórios de Rotinas',
  '/admin/stock/checklists/admin': 'Gestão de Rotinas',
  '/admin/stock/cmv': 'Gestão de CMV',
  '/admin/stock/bonificacoes': 'Bonificações',
  
  // Financeiro (Original Paths)
  '/admin/financeiro': 'Dashboard Financeiro',
  '/admin/financeiro/caixa': 'Caixa & Contas',
  '/admin/financeiro/fluxo': 'Fechamento de Caixa',
  '/admin/financeiro/fluxo-semanal': 'Fluxo Semanal',
  '/admin/financeiro/lancamentos': 'PixPag',
  '/admin/financeiro/receber': 'Contas a Receber',
  '/admin/financeiro/recibos': 'Recibos',
  '/admin/financeiro/despesas': 'Despesas',
  '/admin/financeiro/dre': 'DRE',
  '/admin/financeiro/relatorios': 'Relatórios Financeiros',
  '/admin/financeiro/receitas-despesas': 'Receitas x Despesas',
  '/admin/financeiro/despesas-detalhadas': 'Despesas Detalhadas',
  '/admin/financeiro/cadastros': 'Cadastros Financeiros',
  '/admin/financeiro/configuracoes': 'Configurações Financeiras',

  '/admin/pdv/relatorios': 'Central de Relatórios',
  '/admin/fiscal': 'Fiscal',
  '/admin/fiscal/dashboard': 'Dashboard Fiscal',
  '/admin/fiscal/historico': 'Histórico Fiscal',
  '/admin/analytics': 'Food Analytics',
  '/admin/marketing': 'Campanhas',
  '/admin/feedback': 'Avaliações NPS',
  '/admin/orders/catalog': 'Pedido de Insumos',
  '/admin/orders/history': 'Meus Pedidos',
  '/admin/orders/management': 'Gestão de Cargas',
  '/admin/orders/reports': 'Relatórios',
  '/admin/orders/products': 'Catálogo de Insumos',
  '/admin/franchisees': 'Lista de Franqueados',
  '/admin/loja/dados': 'Dados da Loja',
  '/admin/pdv/configuracoes': 'Configurações PDV',
  '/admin/settings': 'Configurações Gerais',
  '/admin/delivery/areas': 'Áreas de Entrega',
  '/admin/settings/usuarios': 'Usuários & Permissões',
  '/admin/settings/seguranca': 'Segurança do Sistema',
  '/admin/help': 'Manual Operacional',
  '/admin/meu-perfil': 'Meu Perfil',
  '/admin/universidade': 'Universidade',
  '/admin/universidade/admin': 'Gestão de Conteúdo',
  '/admin/frota': 'Controle de Frota',
  '/admin/performance': 'Performance',
  '/admin/assistente': 'GrauBot'
};
