-- ============================================================================
-- RBAC — Sincroniza TODOS os módulos do catálogo do frontend (src/lib/permissions.ts)
-- em rbac_modulos. Corrige de vez o erro ao salvar permissões de usuário:
--   "violates foreign key constraint rbac_usuario_permissoes_modulo_codigo_fkey"
-- que ocorre quando a UI envia um modulo_codigo sem linha-pai em rbac_modulos.
-- Idempotente (ON CONFLICT DO NOTHING) — só insere o que faltar.
-- ============================================================================
INSERT INTO public.rbac_modulos (codigo, nome, categoria, descricao) VALUES
  ('pdv.nova-venda',       'Nova Venda',            'PDV',        'Registro de vendas no balcão'),
  ('pdv.mesas',            'Mesas',                 'PDV',        'Gestão de pedidos por mesa'),
  ('pdv.caixa',            'Caixa',                 'PDV',        'Abertura, sangria e fechamento'),
  ('pdv.historico',        'Histórico PDV',         'PDV',        'Consulta e cancelamento de vendas'),
  ('op.dashboard',         'Dashboard Operacional', 'OPERACAO',   'Visão em tempo real da operação'),
  ('op.pedidos',           'Pedidos Online',        'OPERACAO',   'Gerenciamento de pedidos do app'),
  ('op.kds',               'KDS Cozinha',           'OPERACAO',   'Tela de produção da cozinha'),
  ('op.entregas',          'Entregas',              'OPERACAO',   'Controle de pedidos em rota'),
  ('op.areas-entrega',     'Áreas de Entrega',      'OPERACAO',   'Configuração de zonas e taxas'),
  ('op.frota',             'Frota',                 'OPERACAO',   'Gestão de rotas e entregadores'),
  ('cardapio.cats',        'Categorias',            'CARDAPIO',   'Grupos de produtos no cardápio'),
  ('cardapio.produtos',    'Produtos',              'CARDAPIO',   'Cadastro e disponibilidade'),
  ('cardapio.toppings',    'Complementos',          'CARDAPIO',   'Extras e personalizações'),
  ('cardapio.ingreds',     'Ingredientes',          'CARDAPIO',   'Ingredientes e alérgenos'),
  ('cardapio.promo',       'Promoções',             'CARDAPIO',   'Cupons, descontos e ofertas'),
  ('fin.dashboard',        'Dashboard Financeiro',  'FINANCEIRO', 'Visão consolidada das finanças'),
  ('fin.lancamentos',      'Lançamentos',           'FINANCEIRO', 'Registro de receitas e despesas'),
  ('fin.fluxo-semanal',    'Fluxo Semanal',         'FINANCEIRO', 'Fluxo de caixa dia a dia'),
  ('fin.despesas',         'Despesas',              'FINANCEIRO', 'Gestão e baixa de despesas'),
  ('fin.fechamentos',      'Fechamentos de Caixa',  'FINANCEIRO', 'Histórico de fechamentos por turno'),
  ('fin.dre',              'DRE',                   'FINANCEIRO', 'Demonstrativo de resultado'),
  ('fin.receber',          'Contas a Receber',      'FINANCEIRO', 'Valores pendentes de recebimento'),
  ('fin.cadastros',        'Cadastros Financeiros', 'FINANCEIRO', 'Plano de contas e centros de custo'),
  ('est.central',          'Estoque Central',       'ESTOQUE',    'Cadastro e gestão de insumos'),
  ('est.movimentos',       'Movimentações',         'ESTOQUE',    'Entradas e saídas de estoque'),
  ('est.contagem',         'Contagem Física',       'ESTOQUE',    'Inventário físico semanal'),
  ('est.cmv',              'Gestão de CMV',         'ESTOQUE',    'Custo da mercadoria vendida'),
  ('est.compras',          'Lista de Compras',      'ESTOQUE',    'Reposição por estoque mínimo'),
  ('est.hist-compras',     'Histórico de Compras',  'ESTOQUE',    'Análise de compras por período'),
  ('est.rotinas',          'Rotinas Operacionais',  'ESTOQUE',    'Checklists de abertura e fechamento'),
  ('est.bonificacoes',     'Bonificações',          'ESTOQUE',    'Controle de bonificações de insumos'),
  ('cli.crm',              'Clientes (CRM)',        'CLIENTES',   'Base de clientes e histórico'),
  ('cli.nps',              'Avaliações NPS',        'CLIENTES',   'Satisfação e Net Promoter Score'),
  ('mkt.campanhas',        'Campanhas',             'CLIENTES',   'Push notifications e promoções'),
  ('mkt.analytics',        'Food Analytics',        'CLIENTES',   'Análise avançada de vendas'),
  ('cli.comunidade',       'Comunidade',            'CLIENTES',   'Grupos e engajamento de franqueados'),
  ('caf.dashboard',        'Dashboard CAF',         'CAF',        'Visão geral dos atendimentos'),
  ('caf.atendimentos',     'Atendimentos',          'CAF',        'Abertura e gestão de chamados'),
  ('caf.base-conhecimento','Base de Conhecimento',  'CAF',        'Artigos e soluções documentadas'),
  ('caf.relatorios',       'Relatórios CAF',        'CAF',        'Análise e exportação de dados CAF'),
  ('caf.cadastros',        'Cadastros CAF',         'CAF',        'Cargo, Canal, Categoria e Subcategoria'),
  ('fra.pedidos',          'Pedido de Insumos',     'FRANQUIA',   'Catálogo da distribuidora'),
  ('fra.meus-pedidos',     'Meus Pedidos',          'FRANQUIA',   'Histórico de pedidos à distribuidora'),
  ('mas.cargas',           'Gestão de Cargas',      'FRANQUIA',   'Pedidos das unidades (Master)'),
  ('mas.relatorios',       'Relatórios de Franquia','FRANQUIA',   'Análise detalhada de pedidos e faturamento (Master)'),
  ('mas.catalogo',         'Catálogo de Insumos',   'FRANQUIA',   'Gestão do catálogo (Master)'),
  ('mas.franqueados',      'Franqueados',           'FRANQUIA',   'Lista e gestão de unidades (Master)'),
  ('sis.config-geral',     'Config. Gerais',        'SISTEMA',    'Dados da loja e integrações'),
  ('sis.config-pdv',       'Config. PDV',           'SISTEMA',    'Layout e comportamento do PDV'),
  ('sis.universidade',     'Universidade Grau',     'SISTEMA',    'Trilhas de capacitação'),
  ('sis.usuarios',         'Usuários',              'SISTEMA',    'Cadastro e permissões de usuários'),
  ('sis.uazapi',           'UazAPI / WhatsApp',     'SISTEMA',    'Integração e assistente WhatsApp'),
  ('sis.grauzinho',        'Grauzinho',             'SISTEMA',    'Gamificação e ranking de entregadores')
ON CONFLICT (codigo) DO NOTHING;
