-- ============================================================
-- SCRIPT DE IMPORTAÇÃO: BANCO DE CITAÇÕES GRAUOS (POSTGRES / SUPABASE)
-- Data: 2026-04-21
-- ============================================================

-- 1. CRIAR TABELA DE AUTORES
CREATE TABLE IF NOT EXISTS public.authors (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  birth_year INT,
  death_year INT,
  nationality TEXT,
  main_work TEXT,
  specialty TEXT,
  color TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. CRIAR TABELA DE CATEGORIAS
CREATE TABLE IF NOT EXISTS public.quote_categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  description TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. CRIAR TABELA PRINCIPAL DE CITAÇÕES
CREATE TABLE IF NOT EXISTS public.quotes (
  id TEXT PRIMARY KEY,
  author_id BIGINT NOT NULL REFERENCES public.authors(id) ON DELETE CASCADE,
  category_id BIGINT NOT NULL REFERENCES public.quote_categories(id) ON DELETE CASCADE,
  text TEXT NOT NULL,
  tags JSONB,
  source TEXT,
  is_active BOOLEAN DEFAULT TRUE,
  view_count INT DEFAULT 0,
  favorite_count INT DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_quotes_author ON public.quotes(author_id);
CREATE INDEX IF NOT EXISTS idx_quotes_category ON public.quotes(category_id);
CREATE INDEX IF NOT EXISTS idx_quotes_active ON public.quotes(is_active);

-- 4. CRIAR TABELA DE USO (ANALYTICS)
CREATE TABLE IF NOT EXISTS public.quote_usage (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  quote_id TEXT NOT NULL REFERENCES public.quotes(id) ON DELETE CASCADE,
  franchisee_id UUID REFERENCES auth.users(id),
  campaign_id TEXT,
  context TEXT,
  ip_address TEXT,
  used_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_quote_usage_quote ON public.quote_usage(quote_id);
CREATE INDEX IF NOT EXISTS idx_quote_usage_franchisee ON public.quote_usage(franchisee_id);
CREATE INDEX IF NOT EXISTS idx_quote_usage_used_at ON public.quote_usage(used_at);

-- 5. CRIAR TABELA DE FAVORITOS
CREATE TABLE IF NOT EXISTS public.quote_favorites (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  quote_id TEXT NOT NULL REFERENCES public.quotes(id) ON DELETE CASCADE,
  franchisee_id UUID NOT NULL REFERENCES auth.users(id),
  saved_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE (quote_id, franchisee_id)
);

CREATE INDEX IF NOT EXISTS idx_quote_favorites_franchisee ON public.quote_favorites(franchisee_id);


-- ============================================================
-- ENABLE RLS & POLICIES
-- ============================================================
ALTER TABLE public.authors ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.quote_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.quotes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.quote_usage ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.quote_favorites ENABLE ROW LEVEL SECURITY;

-- Everyone can read authors, categories, quotes:
CREATE POLICY "Public read authors" ON public.authors FOR SELECT USING (true);
CREATE POLICY "Public read categories" ON public.quote_categories FOR SELECT USING (true);
CREATE POLICY "Public read quotes" ON public.quotes FOR SELECT USING (is_active = true);

-- Users can insert usage and manage their own favorites
CREATE POLICY "Insert quote usage" ON public.quote_usage FOR INSERT WITH CHECK (true);
CREATE POLICY "Select quote usage" ON public.quote_usage FOR SELECT USING (franchisee_id = auth.uid());

CREATE POLICY "Manage favorites" ON public.quote_favorites FOR ALL USING (franchisee_id = auth.uid());


-- ============================================================
-- INSERIR AUTORES
-- ============================================================
INSERT INTO public.authors (id, name, birth_year, death_year, nationality, main_work, specialty, color) VALUES
(1, 'Napoleon Hill', 1883, 1970, 'Americano', 'Pense e Enriqueça', 'Desenvolvimento pessoal, Sucesso', '#FAC775'),
(2, 'Seth Godin', 1960, NULL, 'Americano', 'Purple Cow', 'Marketing, Liderança, Negócios', '#9FE1CB'),
(3, 'Stephen King', 1947, NULL, 'Americano', 'On Writing', 'Criatividade, Escrita, Resiliência', '#F4C0D1'),
(4, 'John Maeda', 1966, NULL, 'Japonês-Americano', 'The Laws of Simplicity', 'Design, Tecnologia, Simplicidade', '#B5D4F4'),
(5, 'Steve Jobs', 1955, 2011, 'Americano', 'Biografia (Isaacson)', 'Inovação, Design, Liderança', '#D3D1C7'),
(6, 'Voltaire', 1694, 1778, 'Francês', 'Candide', 'Filosofia, Crítica Social, Ação', '#C0DD97'),
(7, 'John Locke', 1632, 1704, 'Inglês', 'Second Treatise of Government', 'Filosofia, Educação, Liberdade', '#CECBF6'),
(8, 'Katherine Mansfield', 1888, 1923, 'Neozelandesa', 'Diários e Contos', 'Literatura, Propósito, Autenticidade', '#F5C4B3')
ON CONFLICT (id) DO NOTHING;

-- Garantir que a sequência de ID continue corretamente
SELECT setval(pg_get_serial_sequence('public.authors', 'id'), coalesce(max(id)+1, 1), false) FROM public.authors;

-- ============================================================
-- INSERIR CATEGORIAS
-- ============================================================
INSERT INTO public.quote_categories (id, name, description) VALUES
(1, 'Mentalidade', 'Pensamento, crença e atitude pessoal'),
(2, 'Liderança', 'Inspiração, influência e direção de pessoas'),
(3, 'Design', 'Estética, funcionalidade e experiência'),
(4, 'Negócios', 'Empreendimento, vendas e estratégia'),
(5, 'Inovação', 'Criatividade, tecnologia e diferenciação'),
(6, 'Excelência', 'Qualidade, perfeição e refinamento'),
(7, 'Propósito', 'Significado, legado e plenitude'),
(8, 'Ação', 'Fazer, movimento e proatividade'),
(9, 'Resiliência', 'Força, recuperação e transformação'),
(10, 'Comunicação', 'Expressão, narrativa e conexão'),
(11, 'Conhecimento', 'Aprendizado, educação e sabedoria'),
(12, 'Trabalho', 'Dedicação, disciplina e esforço'),
(13, 'Empreendedorismo', 'Risco, coragem e audácia'),
(14, 'Marketing', 'Narrativa, marca e conexão com público'),
(15, 'Metas', 'Planejamento, objetivos e realização')
ON CONFLICT (id) DO NOTHING;

SELECT setval(pg_get_serial_sequence('public.quote_categories', 'id'), coalesce(max(id)+1, 1), false) FROM public.quote_categories;

-- ============================================================
-- INSERIR CITAÇÕES (44 CITAÇÕES)
-- ============================================================
INSERT INTO public.quotes (id, author_id, category_id, text, tags, source) VALUES
-- NAPOLEON HILL
('quote_001', 1, 1, 'Tudo que a mente do homem pode conceber e acreditar, ela pode alcançar.', '["sucesso", "mindset", "crença"]', 'Pense e Enriqueça'),
('quote_002', 1, 2, 'O segredo do sucesso, se é que existe um, é a capacidade de encarar o ponto de vista da outra pessoa e ver as coisas tanto por esse ângulo quanto pelo seu.', '["empatia", "liderança", "sucesso"]', 'Pense e Enriqueça'),
('quote_003', 1, 15, 'Uma meta é um sonho com prazo definido.', '["planejamento", "objetivos", "ação"]', 'Pense e Enriqueça'),
('quote_004', 1, 1, 'Você é o mestre do seu destino. Você é o capitão da sua alma.', '["responsabilidade", "liberdade", "poder"]', 'Pense e Enriqueça'),
('quote_005', 1, 9, 'O fracasso é o caminho de menor resistência.', '["aprendizado", "falha", "crescimento"]', 'Pense e Enriqueça'),
('quote_006', 1, 15, 'Defina seu propósito principal definido e não pare até tê-lo alcançado.', '["persistência", "objetivos", "foco"]', 'Pense e Enriqueça'),

-- SETH GODIN
('quote_007', 2, 14, 'Marketing não é mais sobre as coisas que você faz, mas sobre as histórias que você conta.', '["comunicação", "narrativa", "conexão"]', 'Purple Cow'),
('quote_008', 2, 4, 'As pessoas não compram produtos e serviços. Elas compram relações, histórias e magia.', '["vendas", "relacionamento", "emoção"]', 'Tribes'),
('quote_009', 2, 4, 'Seja notável ou seja invisível.', '["diferenciação", "marca", "posicionamento"]', 'Purple Cow'),
('quote_010', 2, 8, 'A melhor maneira de reclamar é fazer as coisas.', '["proatividade", "mudança", "responsabilidade"]', 'Linchpin'),
('quote_011', 2, 2, 'Liderança é a arte de desistir de algum controle para obter mais.', '["delegação", "confiança", "equipe"]', 'Tribes'),
('quote_012', 2, 13, 'O maior risco é não correr nenhum risco.', '["coragem", "inovação", "oportunidade"]', 'The Dip'),

-- STEPHEN KING
('quote_013', 3, 1, 'A vida não é um filme de apoio. É o principal evento.', '["propósito", "autenticidade", "vida"]', 'On Writing'),
('quote_014', 3, 11, 'Os livros são um modo único de portabilidade. Você pode carregar um milhar de histórias no bolso do seu casaco.', '["aprendizado", "leitura", "crescimento"]', 'On Writing'),
('quote_015', 3, 12, 'Talento é mais barato que sal de mesa. O que separa o indivíduo talentoso do bem-sucedido é muito trabalho árduo.', '["dedicação", "excelência", "sucesso"]', 'On Writing'),
('quote_016', 3, 9, 'O inferno é a impossibilidade da razão.', '["desafio", "lógica", "clareza"]', 'The Stand'),
('quote_017', 3, 8, 'Você pode, você deve, e se for corajoso o suficiente para começar, você vai.', '["coragem", "início", "possibilidade"]', 'On Writing'),

-- JOHN MAEDA
('quote_018', 4, 3, 'Simplicidade é sobre subtrair o óbvio e adicionar o significativo.', '["estética", "funcionalidade", "beleza"]', 'The Laws of Simplicity'),
('quote_019', 4, 3, 'Design é uma solução para um problema. Arte é uma questão para um problema.', '["criatividade", "intencionalidade", "propósito"]', 'The Laws of Simplicity'),
('quote_020', 4, 5, 'A tecnologia sem a alma do design é apenas uma ferramenta.', '["humanidade", "tecnologia", "sensibilidade"]', 'The Laws of Simplicity'),
('quote_021', 4, 3, 'Simplicidade não significa ausência de complexidade — significa que a complexidade foi dominada.', '["profundidade", "mastery", "refinamento"]', 'The Laws of Simplicity'),
('quote_022', 4, 6, 'O design mais simples é frequentemente o mais difícil de alcançar.', '["dedicação", "refinamento", "perfeição"]', 'The Laws of Simplicity'),

-- STEVE JOBS
('quote_023', 5, 5, 'Inovação é o que distingue um líder de um seguidor.', '["criatividade", "visão", "diferenciação"]', 'Palestra em Stanford'),
('quote_024', 5, 3, 'O design não é apenas como parece. Design é como funciona.', '["funcionalidade", "experiência", "intencionalidade"]', 'Biografia'),
('quote_025', 5, 1, 'Sua hora é limitada, então não a desperdice vivendo a vida de outra pessoa.', '["autenticidade", "liberdade", "propósito"]', 'Palestra em Stanford'),
('quote_026', 5, 6, 'Qualidade é mais importante que quantidade. Um home run é muito melhor que dois duplos.', '["padrões", "perfeição", "foco"]', 'Biografia'),
('quote_027', 5, 7, 'Ser o homem mais rico do cemitério não importa para mim. Ir dormir à noite sabendo que fizemos algo maravilhoso, isso importa.', '["legado", "valores", "significado"]', 'Palestra em Stanford'),
('quote_028', 5, 3, 'Simplicidade é a sofisticação máxima.', '["elegância", "refinamento", "beleza"]', 'Biografia'),

-- VOLTAIRE
('quote_029', 6, 6, 'O melhor é o inimigo do bom.', '["pragmatismo", "satisfação", "ação"]', 'Candide'),
('quote_030', 6, 2, 'Cada homem é culpado pelo bem que não fez.', '["responsabilidade", "ação", "impacto"]', 'Ensaios Filosóficos'),
('quote_031', 6, 12, 'Trabalho afasta de nós três grandes males: o tédio, o vício e a necessidade.', '["propósito", "disciplina", "bem-estar"]', 'Candide'),
('quote_032', 6, 10, 'O segredo de ser chato é dizer tudo.', '["eloquência", "síntese", "impacto"]', 'Ensaios Filosóficos'),
('quote_033', 6, 11, 'A incerteza é desconfortável, mas a certeza é ridícula.', '["humildade", "aprendizado", "abertura"]', 'Ensaios Filosóficos'),
('quote_034', 6, 7, 'Apreciamos o que criamos.', '["criação", "valor", "significado"]', 'Ensaios Filosóficos'),

-- JOHN LOCKE
('quote_035', 7, 11, 'Educação começa pelo bebê e nunca termina.', '["desenvolvimento", "aprendizado", "crescimento"]', 'Some Thoughts Concerning Education'),
('quote_036', 7, 2, 'Onde não há lei, não há liberdade.', '["estrutura", "responsabilidade", "ordem"]', 'Second Treatise of Government'),
('quote_037', 7, 7, 'O propósito da lei não é abolir ou restringir, mas preservar e ampliar a liberdade.', '["justiça", "direitos", "desenvolvimento"]', 'Second Treatise of Government'),
('quote_038', 7, 1, 'Nenhum homem pode ser obrigado a fazer o que não é para o seu bem.', '["autonomia", "bem-estar", "dignidade"]', 'Some Thoughts Concerning Education'),
('quote_039', 7, 8, 'As ações dos homens são os melhores intérpretes de seus pensamentos.', '["autenticidade", "coerência", "verdade"]', 'Essay Concerning Human Understanding'),

-- KATHERINE MANSFIELD
('quote_040', 8, 6, 'Fazer algo de um modo diferente, melhor — isso é o que quero.', '["inovação", "melhoria", "ambição"]', 'Diários e Cartas'),
('quote_041', 8, 7, 'Quanto tempo leva para saber que amamos algo? Um momento.', '["paixão", "intuição", "clareza"]', 'Diários e Cartas'),
('quote_042', 8, 9, 'É preciso coragem para crescer e se tornar quem você realmente é.', '["autenticidade", "transformação", "coragem"]', 'Diários e Cartas'),
('quote_043', 8, 13, 'Risco! Arrisque qualquer coisa! Cuidar não mais, tenha medo não mais, mas ria de todos os medos.', '["audácia", "liberdade", "ação"]', 'Diários e Cartas'),
('quote_044', 8, 7, 'O que queremos é descobrir o que vai fazer da vida uma coisa completa.', '["significado", "plenitude", "busca"]', 'Diários e Cartas')
ON CONFLICT (id) DO NOTHING;

-- ============================================================
-- CRIAR ROTINA (RPC) PARA BUSCAR UMA CITAÇÃO ALEATÓRIA
-- ============================================================
CREATE OR REPLACE FUNCTION get_random_quote(p_category_id BIGINT DEFAULT NULL)
RETURNS TABLE (
  id TEXT,
  text TEXT,
  author_name TEXT,
  author_color TEXT,
  category_name TEXT,
  source TEXT
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  RETURN QUERY
  SELECT 
    q.id,
    q.text,
    a.name AS author_name,
    a.color AS author_color,
    c.name AS category_name,
    q.source
  FROM public.quotes q
  JOIN public.authors a ON q.author_id = a.id
  JOIN public.quote_categories c ON q.category_id = c.id
  WHERE q.is_active = TRUE
    AND (p_category_id IS NULL OR q.category_id = p_category_id)
  ORDER BY RANDOM()
  LIMIT 1;
END;
$$;
